rvm: 1.8.7
bundler_args: ''
notifications:
  hipchat:
    rooms:
      secure: HO8IqVJxCgOVCVb8k7qPX1HG6i6k9/iGRfyu1n4Tt0egXhjrUqG4MU5lR8ZYjzN0oqeEM9MrDdKwtStm9vJbQZYXI+3g6cToEh936x5kxd2fhFxPYcDP369mZ81r2X4l3V2jXrCFiELAE5xixEiC1BI9wbFW8HoD+5KRcejgtYQ=
env:
- PUPPET_VERSION=3.4.2
- PUPPET_VERSION=3.3.1
- PUPPET_VERSION=3.2.3
- PUPPET_VERSION=2.7.21
